version: '3.8'
services:
  optiemp:
    image: 'optiemp-prod:latest'
    build:
      context: ./
      args:
        PROFILE: prod
    container_name: optiemp
    restart: always
    ports:
      - '8010:80'